### PR TITLE
Fix wrong paths on case sensitive systems

### PR DESCRIPTION
**Pull request by akien-mga**
- Renamed `Main.tscn` to `main.tscn` to match path in `project.godot`.
- Fixed path to texture in its `.import` file; can't rename the `Textures` folder to lowercase without changing the .glb's it seems.
- Removed temporary file.

The change to the binary `cloud.res` seems gratuitous and a Godot bug, I've seen it on another project but couldn't figure out yet how to solve it for good. That means that when people clone the report and import it for the first time, they may also see this file change. Since it's binary, one can't see why it's changing.

Nothing for you to fix/work around easily, that's a bug we need to fix upstream.

### CODE REVIEW

**Comment by KenneyNL** [comment]
Thanks for the fixes! I'll keep the rename issues in mind next time I'm doing a project, seems like a lot of issues came from me just renaming folders and files.

**Comment by akien-mga** [comment]
> The change to the binary `cloud.res` seems gratuitous and a Godot bug, I've seen it on another project but couldn't figure out yet how to solve it for good. That means that when people clone the report and import it for the first time, they may also see this file change. Since it's binary, one can't see why it's changing.

So actually it's not a bug per se, but a sort of misfeature.

The `cloud.glb` model uses the `save_to_file` option to extract the cloud mesh to `cloud.res`. This doesn't appear to be deterministic, so every time the `.godot` folder is cleared, or the asset is manually reimported, the `cloud.res` file changes (in practice there's no functional change, probably just the UID changing).

**Comment by KenneyNL** [comment]
Okay so I might've messed that up completely, I'll see if I can just find another way to do this which is less bug/misfeature-like.

**Comment by akien-mga** [comment]
> Okay so I might've messed that up completely, I'll see if I can just find another way to do this which is less bug/misfeature-like.

No you used the feature the way it's meant to be used. That's just a quirk we need to solve upstream.

It can be worked around in your project by e.g. not extracting the mesh to a separate file, but I haven't looked in depth what that would imply. It's probably fine as is for the time being, it's just a quirk.

**Comment by Alex2782** [comment]
my macOS changes the file 'prefabs/coin_prefab.tscn'.

`Godot v4.1.1.stable - macOS 13.5.2`

image

**Pull request merged**
