### PR TITLE
CSharp Port

### PR DESCRIPTION
**Pull request by LauraWebdev**
I wasn't able to select a new branch as the merge target, but here is a full port to C# of the project.
It uses as many best practices of the language while keeping variable names and functionality as close as it can be.

One notable change has been a simplification of the Audio queue system, which uses Linq to select unused AudioStreamPlayers without needing to maintain a second array.

### CODE REVIEW

**Comment by KenneyNL** [comment]
Wow, fantastic and so fast! I'm not sure what to do with this though, I'm a git noob... what do I do to make this available to people?

**Comment by LauraWebdev** [comment]
Yeah, I was surprised how fast it was as well!

You could create a new branch and change this PR to point to that branch.
If you want, you can invite me to the project temporarily and I'll switch the branch.

**Comment by LauraWebdev** [comment]
I'll also have a look at the two commits that came in since then and adapt accordingly!

**Comment by LauraWebdev** [comment]
Just cherry-picked the two commits to sync up the branch.

**Comment by DmytroJDS** [comment]
Thanks for porting, really useful for c# devs. :)

**Comment by stephannv** [comment]
One suggestion @LauraWebdev: You can fork the repo and keep it updated with the changes here. Then @KenneyNL add a link to your repo on README.md. If other people want to made alternative versions (eg. using lua, rust, haxe, etc) , this will be aggregated in a single section, and takes the burden of maintaining multiple projects off this repository.

**Comment by ElMikosch** [comment]
Hi @LauraWebdev,
thanks for your work on porting this project to C#. One suggestion: In the [Godot C# style guidelines](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_style_guide.html#naming-conventions), it's recommended to use an underscore as a prefix for private fields. Considering this project's potential as a starting point, would you be open to aligning with this convention? Let me know your thoughts.

**Comment by LauraWebdev** [comment]
> Hi @LauraWebdev,
> thanks for your work on porting this project to C#. One suggestion: In the [Godot C# style guidelines](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_style_guide.html#naming-conventions), it's recommended to use an underscore as a prefix for private fields. Considering this project's potential as a starting point, would you be open to aligning with this convention? Let me know your thoughts.

Absolutely, I've used the default style hints from Rider so far but I'd be down to change it up.

**Comment by jasonswearingen** [comment]
IMO, making style changes like prefixing underscore should not hold up acceptance of a feature PR like this.  followup with a style PR if that's deemed needed (I don't think it is....)

**Comment by LauraWebdev** [comment]
> IMO, making style changes like prefixing underscore should not hold up acceptance of a feature PR like this. followup with a style PR if that's deemed needed (I don't think it is....)

CSharp and gdscript are very different programming languages, and while maintaining code similarity is important, teaching people to use the best practices of the chosen programming language are equally important, especially in a demo project aimed at beginners.

**Pull request closed without merging**
